<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <RootNamespace>DinClassLibrary</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Castle.Windsor" Version="6.0.0" />
      <PackageReference Include="QuikGraph" Version="2.5.0" />
    </ItemGroup>

</Project>
