window.data = [
    {
        id: 1,
        naam: "34 Rue du Dr Roux 15B",
        images: [
            "../media/appartementen/detailed/appd1.webp",
            "../media/appartementen/detailed/appd2.webp",
            "../media/appartementen/detailed/appd3.webp",
            "../media/appartementen/detailed/appd4.webp",
            "../media/appartementen/detailed/appd5.webp",
            "../media/appartementen/detailed/appd6.webp",
            "../media/appartementen/detailed/appd7.webp",
        ],
        altImages: [
            "living",
            "eettafel",
            "zetel",
            "keuken en voordeur",
            "keuken",
            "haard",
            "haard naast raam",
        ],
        price: 564200,
        energie: "A",
        heating: "electric",
        locatie: "Parijs",
        oppervlakte: "60m2",
        aantal: {
            kamers: 4,
            slaapkamers: 2,
            badkamers: 1,
        },
        paragraphs: {
            titles: [
                "Modern Apartment in het hartje van Parijs",
                "Ruime and heldere living kamer",
                "De ideale locatie",
            ],
            text: [
                "Dit prachtige appartement is gelegen in een van de meest gewilde wijken van Parijs, op loopafstand van de Eiffeltoren, de Champs-Élysées en het Louvre. Het appartement is onlangs gerenoveerd en heeft een moderne uitstraling, met een volledig uitgeruste keuken, een luxe badkamer en een gezellige slaapkamer.",
                "Het appartement heeft een oppervlakte van 60 m2 en is geschikt voor maximaal vier personen. De woonkamer is ruim en licht, met een comfortabele bank, een eettafel en een flatscreen-tv. De keuken is voorzien van een koelkast, een oven, een magnetron, een vaatwasser en een koffiezetapparaat. De badkamer heeft een inloopdouche, een wastafel en een toilet. De slaapkamer heeft een tweepersoonsbed, een kledingkast en een bureau.",
                "Het appartement is ideaal voor iemand die wil genieten van het bruisende leven in Parijs, met tal van restaurants, cafés, winkels en culturele attracties in de buurt. Het appartement is ook goed bereikbaar met het openbaar vervoer, met een metrostation en een bushalte op slechts een paar minuten lopen. Het appartement is beschikbaar voor een koopprijs van €564.200, inclusief servicekosten en internet. Vul vandaag het formulier nog in om een bezoek te plannen",
            ],
        },
    },
    {
        id: 2,
        naam: "58 Rue Lemercier",
        images: [
            "../media/rijhuis/detail/rijd1.jpg",
            "../media/rijhuis/detail/rijd2.jpg",
            "../media/rijhuis/detail/rijd3.jpg",
            "../media/rijhuis/detail/rijd4.jpg",
            "../media/rijhuis/detail/rijd5.jpg",
            "../media/rijhuis/detail/rijd6.jpg",
            "../media/rijhuis/detail/rijd7.jpg",
            "../media/rijhuis/detail/rijd8.jpg",
        ],
        altImages: [
            "living",
            "living en tv",
            "keuken",
            "2de living",
            "2de living met bar",
            "slaapkamer",
            "badkamer",
            "voordeur",
        ],
        price: 1180000,
        energie: "B",
        heating: "gas",
        locatie: "Parijs",
        oppervlakte: "146m2",
        aantal: {
            kamers: 8,
            slaapkamers: 4,
            badkamers: 2,
        },
        paragraphs: {
            titles: [
                "Een oase van rust en luxe",
                "Vier slaapkamers en een volledig uitgeruste keuken",
                "Een rustige en groene buurt",
            ],
            text: [
                "Ontdek een oase van rust en luxe met deze prachtige woning, voorzien van een ruime, lichtovergoten woonkamer en een uitnodigende tweede woonkamer met een prachtige afrikaanse afwerking. De moderne inrichting en topafwerkingen beloven een exclusieve levensstijl. Laat deze kans niet liggen om het huis van uw dromen te bezitten!",
                "De woning beschikt over vier slaapkamers, waarvan de hoofdslaapkamer een eigen badkamer en een inloopkast heeft. De andere drie slaapkamers delen een tweede badkamer met een ligbad en een douche. De keuken is volledig uitgerust met hoogwaardige apparatuur en een gezellige eethoek. De woning heeft ook een aparte wasruimte, een berging en een garage.",
                "De woning is gelegen in een rustige en groene buurt, dicht bij winkels, scholen, parken en openbaar vervoer. Het centrum van Antwerpen is gemakkelijk bereikbaar met de auto of de fiets. De woning is gebouwd in 2020 en verkeert in uitstekende staat. De woning is energiezuinig en voorzien van zonnepanelen, dubbele beglazing en vloerverwarming.",
            ],
        },
    },
    {
        id: 3,
        naam: "Paleis van Versailles",
        images: [
            "../media/villa/detail/vild1.jpg",
            "../media/villa/detail/vild2.jpg",
            "../media/villa/detail/vild3.jpg",
            "../media/villa/detail/vild4.jpg",
            "../media/villa/detail/vild5.jpg",
            "../media/villa/detail/vild6.png",
            "../media/villa/detail/vild7.jpg",
            "../media/villa/detail/vild8.jpg",
            "../media/villa/detail/vild9.jpg",
        ],
        altImages: [
            "spiegel kamer",
            "buiten",
            "kamer 341",
            "kamer 685",
            "slaapkamer 154",
            "tuinhuis 7",
            "fontein 74",
            "fontein 9",
            "luchtfoto",
        ],
        price: 2540000000,
        energie: "D",
        heating: "wood",
        locatie: "Versailles",
        oppervlakte: "63.154m2",
        aantal: {
            kamers: 2300,
            slaapkamers: 985,
            badkamers: 452,
        },
        paragraphs: {
            titles: [
                "Een unieke en luxueuze woning in Frankrijk",
                "Een meesterwerk van de Franse barokke stijl",
                "De perfecte plek om te wonen, te werken en te genieten",
            ],
            text: [
                "Bent u op zoek naar een unieke en luxueuze woning in Frankrijk? Dan is het Paleis van Versailles iets voor u! Dit prachtige paleis is net gebouwd en heeft een oppervlakte van meer dan 60.000 m2 Het paleis heeft 2.300 kamers, 2.000 ramen, 1.200 open haarden, 67 trappen en 5.000 meubelstukken. Het is omgeven door een schitterende tuin van 800 hectare, met fonteinen, vijvers, standbeelden en bloemen.",
                "Het Paleis van Versailles is ontworpen door de beroemde architect Louis Le Vau, die ook het Louvre heeft gebouwd. Het paleis is een meesterwerk van de Franse barokke stijl, met gouden details, marmeren vloeren, kristallen kroonluchters, zijden gordijnen en schilderijen van de grootste kunstenaars. Het paleis heeft ook een kapel, een operatheater, een spiegelzaal en een koninklijke bibliotheek.",
                "Het Paleis van Versailles is de perfecte plek om te wonen als u houdt van elegantie, comfort en prestige. U kunt genieten van het uitzicht op de tuin vanuit uw slaapkamer, ontspannen in uw privé-spa, dineren in uw ruime eetzaal of feesten in uw balzaal. Het paleis is ook geschikt voor zakelijke bijeenkomsten, culturele evenementen of diplomatieke missies. Wacht niet langer en neem vandaag nog contact op met ons makelaarskantoor om een bezichtiging te regelen. Het Paleis van Versailles wacht op u!",
            ],
        },
    },
];